version: '3'
services:
  ng-peygold:
    container_name: ng-peygold
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    working_dir: /app
    ports:
      - '4201:4200' ### Angular development server
      - '9876:9876' ### Angular hot-reload
      - '9005:9005' ### Firebase cli
    volumes:
    - ./:/app:rw
    networks:
    - peygold-network

#Docker Networks
networks:
  peygold-network:
    driver: bridge
