version: '3'
services:
  ng-peygold:
    container_name: ng-peygold
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    working_dir: /app
    ports:
      - '4201:4200'
      - '9876:9876'
    volumes:
    - ./:/app:rw
    networks:
    - peygold-network

#Docker Networks
networks:
  peygold-network:
    driver: bridge
